"""
Compares the graph-based and embeddings-based grounding retrievers on the
same set of questions.

Reports three things:

1. Structural column match (graph only)
   Precision/recall against GroundingResult.columns.

2. Context grounding recall (both backends)
   Checks whether the expected column name, or its human-readable name,
   appears in the returned context.

3. Latency per call (both backends).

The expected column mappings are based on the live SQLite schema and the
ESG knowledge graph JSON used by the graph retriever.
"""

import time
from dataclasses import dataclass, field
from pathlib import Path

from grounding.base import GroundingResult
from grounding.embedding_retriever import EmbeddingGroundingRetriever
from grounding.graph_retriever import GraphRetriever

PROJECT_ROOT = Path(__file__).resolve().parents[2]

KNOWLEDGE_GRAPH_PATH = PROJECT_ROOT / "data" / "esg_knowledge.json"


# ---------------------------------------------------------------------
# Test cases
# ---------------------------------------------------------------------
# The benchmark covers:
#
# - Direct KPI aliases
# - Business-level synonyms
# - Multiple KPI mappings
# - Dimension grounding
# - Phrasing variations
# - Compliance metrics
# - Pure dimension questions
#
# ---------------------------------------------------------------------

TEST_CASES = [
    # ---------------------------------------------------------------
    # Direct KPI + dimension
    # ---------------------------------------------------------------
    {
        "question": "Show Scope 1 emissions by country",
        "expected_columns": {
            "Scope1_Emissions",
            "Country",
        },
    },
    {
        "question": "Show carbon footprint by facility",
        "expected_columns": {
            "Scope1_Emissions",
            "Scope2_Emissions",
            "Scope3_Emissions",
            "Facility_Name",
        },
    },
    {
        "question": "Show waste generated by industry",
        "expected_columns": {
            "Waste_Generated_Tons",
            "Industry",
        },
    },
    {
        "question": "Show employee attrition by country",
        "expected_columns": {
            "Employee_Turnover_Percentage",
            "Country",
        },
    },
    # ---------------------------------------------------------------
    # Business synonyms / umbrella concepts
    # ---------------------------------------------------------------
    {
        "question": "Show water withdrawal by facility",
        "expected_columns": {
            "Water_Withdrawal_m3",
            "Facility_Name",
        },
    },
    {
        "question": "Show carbon emissions by country",
        "expected_columns": {
            "Scope1_Emissions",
            "Scope2_Emissions",
            "Scope3_Emissions",
            "Country",
        },
    },
    {
        "question": "Show green energy adoption by country",
        "expected_columns": {
            "Renewable_Energy_Percentage",
            "Country",
        },
    },
    {
        "question": "Show gender diversity by country",
        "expected_columns": {
            "Female_Workforce_Percentage",
            "Country",
        },
    },
    # ---------------------------------------------------------------
    # Compliance
    # ---------------------------------------------------------------
    {
        "question": "Show compliance violations by facility",
        "expected_columns": {
            "Compliance_Violations",
            "Facility_Name",
        },
    },
    {
        "question": "Which facilities had the most compliance incidents",
        "expected_columns": {
            "Compliance_Violations",
            "Facility_Name",
        },
    },
    # ---------------------------------------------------------------
    # Workforce / dimension variation
    # ---------------------------------------------------------------
    {
        "question": "Compare employee count by facility",
        "expected_columns": {
            "Employee_Count",
            "Facility_Name",
        },
    },
    {
        "question": "Show headcount by country",
        "expected_columns": {
            "Employee_Count",
            "Country",
        },
    },
    {
        "question": "Show women representation by industry",
        "expected_columns": {
            "Female_Workforce_Percentage",
            "Industry",
        },
    },
    # ---------------------------------------------------------------
    # Pure dimension lookup
    # ---------------------------------------------------------------
    {
        "question": "List facilities in Germany",
        "expected_columns": {
            "Country",
            "Facility_Name",
        },
    },
    # ---------------------------------------------------------------
    # Phrasing variation
    # ---------------------------------------------------------------
    {
        "question": "Which plants have the highest employee attrition?",
        "expected_columns": {
            "Employee_Turnover_Percentage",
            "Facility_Name",
        },
    },
    {
        "question": "Show freshwater usage by site",
        "expected_columns": {
            "Water_Withdrawal_m3",
            "Facility_Name",
        },
    },
    {
        "question": "Compare waste output across sectors",
        "expected_columns": {
            "Waste_Generated_Tons",
            "Industry",
        },
    },
]


# ---------------------------------------------------------------------
# Column -> human-readable name
# ---------------------------------------------------------------------
# Built directly from the knowledge graph so the benchmark does not
# maintain a second KPI/dimension mapping manually.
# ---------------------------------------------------------------------


def build_column_to_name_map(
    graph_retriever: GraphRetriever,
) -> dict[str, str]:

    mapping: dict[str, str] = {}

    for kpi in graph_retriever.kpis.values():
        mapping[kpi["column"]] = kpi["name"]

    for dimension in graph_retriever.dimensions.values():
        mapping[dimension["column"]] = dimension["column"]

    return mapping


# ---------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------


@dataclass
class CaseResult:
    question: str
    expected: set[str]
    latency_ms: float
    context: str

    # None for embedding retriever because it does not return
    # structured column mappings.
    structural_actual: set[str] | None = None

    containment_hits: set[str] = field(default_factory=set)

    @property
    def structural_precision(self) -> float | None:

        if self.structural_actual is None:
            return None

        if not self.structural_actual:
            return 0.0 if self.expected else 1.0

        return len(self.expected & self.structural_actual) / len(self.structural_actual)

    @property
    def structural_recall(self) -> float | None:

        if self.structural_actual is None:
            return None

        if not self.expected:
            return 1.0 if not self.structural_actual else 0.0

        return len(self.expected & self.structural_actual) / len(self.expected)

    @property
    def containment_recall(self) -> float:

        if not self.expected:
            return 1.0

        return len(self.containment_hits) / len(self.expected)


# ---------------------------------------------------------------------
# Context matching
# ---------------------------------------------------------------------


def text_contains_column(
    context: str,
    column: str,
    human_name: str,
) -> bool:

    context_lower = context.lower()

    return column.lower() in context_lower or human_name.lower() in context_lower


def evaluate_case(
    case: dict,
    result: GroundingResult,
    latency_ms: float,
    column_to_name: dict[str, str],
    is_graph: bool,
) -> CaseResult:

    expected = case["expected_columns"]

    containment_hits = {
        column
        for column in expected
        if text_contains_column(
            result.context,
            column,
            column_to_name.get(column, column),
        )
    }

    return CaseResult(
        question=case["question"],
        expected=expected,
        latency_ms=latency_ms,
        context=result.context,
        structural_actual=(set(result.columns) if is_graph else None),
        containment_hits=containment_hits,
    )


# ---------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------


def run(
    retriever,
    label: str,
    column_to_name: dict[str, str],
    is_graph: bool,
    warm_up: bool = False,
) -> list[CaseResult]:

    if warm_up:
        # Model load (e.g. BGE weights) happens lazily on first call.
        # Charging that one-time cold-start cost to a single test
        # question skews the average latency by orders of magnitude
        # relative to steady-state production behavior, where the
        # model is loaded once at process startup. Run one throwaway
        # call before timing starts.
        retriever.retrieve(TEST_CASES[0]["question"])

    results: list[CaseResult] = []

    for case in TEST_CASES:
        start = time.perf_counter()
        grounding = retriever.retrieve(case["question"])
        latency_ms = (time.perf_counter() - start) * 1000

        results.append(
            evaluate_case(case, grounding, latency_ms, column_to_name, is_graph)
        )

    print(f"\n{'=' * 80}")
    print(label)
    print("=" * 80)

    avg_containment = sum(r.containment_recall for r in results) / len(results)
    avg_latency = sum(r.latency_ms for r in results) / len(results)

    print(f"Avg context grounding recall: {avg_containment:.2f}")
    print(f"Avg latency (post-warm-up):   {avg_latency:.1f} ms")

    if is_graph:
        structural_results = [r for r in results if r.structural_recall is not None]
        avg_struct_precision = sum(
            r.structural_precision for r in structural_results
        ) / len(structural_results)
        avg_struct_recall = sum(r.structural_recall for r in structural_results) / len(
            structural_results
        )
        print(f"Avg structural precision:     {avg_struct_precision:.2f}")
        print(f"Avg structural recall:        {avg_struct_recall:.2f}")

    print("\nPer-question results:")
    for r in results:
        flag = "OK" if r.containment_recall == 1.0 else "MISS"
        structural = (
            f"  structural={sorted(r.structural_actual)}"
            if r.structural_actual is not None
            else ""
        )
        print(
            f"  [{flag}] '{r.question}'"
            f"\n         expected={sorted(r.expected)}"
            f"  containment_hits={sorted(r.containment_hits)}"
            f"{structural}"
            f"  latency={r.latency_ms:.1f}ms"
        )

    return results


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------


def main() -> None:

    graph_retriever = GraphRetriever(KNOWLEDGE_GRAPH_PATH)

    column_to_name = build_column_to_name_map(graph_retriever)

    run(
        graph_retriever,
        "GRAPH RETRIEVER",
        column_to_name,
        is_graph=True,
    )

    embedding_retriever = EmbeddingGroundingRetriever()

    run(
        embedding_retriever,
        "EMBEDDING RETRIEVER",
        column_to_name,
        is_graph=False,
        warm_up=True,
    )


if __name__ == "__main__":
    main()
