from grounding.embedding_retriever import EmbeddingGroundingRetriever

retriever = EmbeddingGroundingRetriever()


questions = [
    "Show Scope 1 emissions by country",
    "Show carbon footprint by facility",
    "Show green energy adoption by country",
    "Show gender diversity by country",
    "Show employee attrition by country",
    "Show water withdrawal by facility",
    "Show waste generated by industry",
]


print("=" * 80)
print("EMBEDDING GROUNDING RETRIEVER TEST")
print("=" * 80)


for question in questions:

    result = retriever.retrieve(question)

    print("\nQuestion:")
    print(question)

    print("\nContext:")
    print(result.context)

    print("-" * 80)
