from pathlib import Path

from grounding.graph_retriever import GraphRetriever

PROJECT_ROOT = Path(__file__).resolve().parents[2]

KNOWLEDGE_PATH = PROJECT_ROOT / "data" / "esg_knowledge.json"


retriever = GraphRetriever(KNOWLEDGE_PATH)


QUESTIONS = [
    "Show Scope 1 emissions by country",
    "Show carbon footprint by facility",
    "Show carbon emissions by country",
    "Show green energy adoption by country",
    "Show gender diversity by country",
    "Show employee attrition by country",
    "Show water withdrawal by facility",
    "Show waste generated by industry",
]


print("=" * 80)
print("GRAPH GROUNDING RETRIEVER TEST")
print("=" * 80)


for question in QUESTIONS:

    result = retriever.retrieve(question)

    print("\nQuestion:")
    print(question)

    print("\nMatched terms:")
    print(result.matched_terms)

    print("\nColumns:")
    print(result.columns)

    print("\nContext:")
    print(result.context)

    print("-" * 80)
